In [4]:
import datetime
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows',None)
df1 = pd.read_csv('./csv_files/idx.csv', parse_dates=True, index_col=0)

df1

                 display_name    name  start_date    end_date   type
000001.XSHG              上证指数    SZZS  1991-07-15  2200-01-01  index
000002.XSHG              A股指数    AGZS  1992-02-21  2200-01-01  index
000003.XSHG              B股指数    BGZS  1992-02-21  2200-01-01  index
000004.XSHG              工业指数    GYZS  1993-05-03  2200-01-01  index
000005.XSHG              商业指数    SYZS  1993-05-03  2200-01-01  index
000006.XSHG              地产指数    DCZS  1993-05-03  2200-01-01  index
000007.XSHG              公用指数    GYZS  1993-05-03  2200-01-01  index
000008.XSHG              综合指数    ZHZS  1993-05-03  2200-01-01  index
000009.XSHG             上证380   SZ380  2010-11-29  2200-01-01  index
000010.XSHG             上证180   SZ180  2002-07-01  2200-01-01  index
000011.XSHG              基金指数    JJZS  2000-06-09  2200-01-01  index
000012.XSHG              国债指数    GZZS  2003-01-02  2200-01-01  index
000013.XSHG           上证企业债指数    QZZS  2003-06-09  2020-12-28  index
000015.XSHG              红利指数    HLZS  2005-01-04  2200-01-01  index
000016.XSHG              上证50    SZ50  2004-01-02  2200-01-01  index
000017.XSHG               新综指     XZZ  2006-01-04  2200-01-01  index
000018.XSHG             180金融   180JR  2007-12-10  2200-01-01  index
000019.XSHG              治理指数    ZLZS  2008-01-02  2200-01-01  index
000020.XSHG              中型综指    ZXZZ  2008-05-12  2200-01-01  index
000021.XSHG             180治理   180ZL  2008-09-10  2200-01-01  index
000022.XSHG           上证公司债指数    HGSZ  2008-11-19  2200-01-01  index
000025.XSHG             180基建   180JJ  2008-12-15  2200-01-01  index
000026.XSHG             180资源   180ZY  2008-12-15  2200-01-01  index
000027.XSHG             180运输   180YS  2008-12-15  2200-01-01  index
000028.XSHG             180成长   180CZ  2009-01-09  2200-01-01  index
000029.XSHG             180价值   180JZ  2009-01-09  2200-01-01  index
000030.XSHG            180R成长  180RCZ  2009-01-09  2200-01-01  index
000031.XSHG            180R价值  180RJZ  2009-01-09  2200-01-01  index
000032.XSHG              上证能源    SZNY  2009-01-09  2200-01-01  index
000033.XSHG              上证材料    SZCL  2009-01-09  2200-01-01  index
000034.XSHG              上证工业    SZGY  2009-01-09  2200-01-01  index
000035.XSHG              上证可选    SZKX  2009-01-09  2200-01-01  index
000036.XSHG              上证消费    SZXF  2009-01-09  2200-01-01  index
000037.XSHG              上证医药    SZYY  2009-01-09  2200-01-01  index
000038.XSHG              上证金融    SZJR  2009-01-09  2200-01-01  index
000039.XSHG              上证信息    SZXX  2009-01-09  2200-01-01  index
000040.XSHG              上证电信    SZDX  2009-01-09  2200-01-01  index
000041.XSHG              上证公用    SZGY  2009-01-09  2200-01-01  index
000042.XSHG              上证央企    SZYQ  2009-03-30  2200-01-01  index
000043.XSHG               超大盘     CDP  2009-04-23  2200-01-01  index
000044.XSHG              上证中盘    SZZP  2009-07-03  2200-01-01  index
000045.XSHG              上证小盘    SZXP  2009-07-03  2200-01-01  index
000046.XSHG              上证中小    SZZX  2009-07-03  2200-01-01  index
000047.XSHG              上证全指    SZQZ  2009-07-03  2200-01-01  index
000048.XSHG              责任指数    ZRZS  2009-08-05  2200-01-01  index
000049.XSHG              上证民企    SZMQ  2009-08-25  2200-01-01  index
000050.XSHG              50等权    50DQ  2011-01-04  2200-01-01  index
000051.XSHG             180等权   180DQ  2011-05-24  2200-01-01  index
000052.XSHG              50基本    50JB  2012-01-09  2200-01-01  index
000053.XSHG             180基本   180JB  2012-01-09  2200-01-01  index
000054.XSHG              上证海外    SZHW  2010-01-04  2200-01-01  index
000055.XSHG              上证地企    SZDQ  2010-01-04  2200-01-01  index
000056.XSHG              上证国企    SZGQ  2010-01-04  2200-01-01  index
000057.XSHG              全指成长    QZCZ  2010-01-04  2200-01-01  index
000058.XSHG              全指价值    QZJZ  2010-01-04  2200-01-01  index
000059.XSHG              全R成长    QRCZ  2010-01-04  2200-01-01  index
000060.XSHG              全R价值    QRJZ  2010-01-04  2200-01-01  index
000061.XSHG             沪企债30   HQZ30  2010-01-04  2200-01-01  index
000062.XSHG              上证沪企    SZHQ  2010-01-04  2200-01-01  index
000063.XSHG              上证周期    SZZQ  2010-02-03  2200-01-01  index
000064.XSHG               非周期     FZQ  2010-02-03  2200-01-01  index
000065.XSHG              上证龙头    SZLT  2010-02-09  2200-01-01  index
000066.XSHG              上证商品    SZSP  2010-04-30  2200-01-01  index
000067.XSHG              上证新兴    SZXX  2010-04-30  2200-01-01  index
000068.XSHG              上证资源    SZZY  2010-05-28  2200-01-01  index
000069.XSHG              消费80    XF80  2010-05-28  2200-01-01  index
000070.XSHG              能源等权    NYDQ  2010-08-18  2200-01-01  index
000071.XSHG              材料等权    CLDQ  2010-08-18  2200-01-01  index
000072.XSHG              工业等权    GYDQ  2010-08-18  2200-01-01  index
000073.XSHG              可选等权    KXDQ  2010-08-18  2200-01-01  index
000074.XSHG              消费等权    XFDQ  2010-08-18  2200-01-01  index
000075.XSHG              医药等权    YYDQ  2010-08-18  2200-01-01  index
000076.XSHG              金融等权    JRDQ  2010-08-18  2200-01-01  index
000077.XSHG              信息等权    XXDQ  2010-08-18  2200-01-01  index
000078.XSHG              电信等权    DXDQ  2010-08-18  2200-01-01  index
000079.XSHG              公用等权    GYDQ  2010-08-18  2200-01-01  index
000090.XSHG              上证流通    SZLT  2010-12-02  2200-01-01  index
000091.XSHG              沪财中小    HCZX  2011-04-06  2200-01-01  index
000092.XSHG              资源50    ZY50  2011-05-10  2200-01-01  index
000093.XSHG             180分层   180FC  2011-05-24  2200-01-01  index
000094.XSHG              上证上游    SZSY  2011-05-10  2200-01-01  index
000095.XSHG              上证中游    SZZY  2011-05-10  2200-01-01  index
000096.XSHG              上证下游    SZXY  2011-05-10  2200-01-01  index
000097.XSHG              高端装备    GDZB  2011-05-24  2200-01-01  index
000098.XSHG            上证F200  SZF200  2011-07-01  2200-01-01  index
000099.XSHG            上证F300  SZF300  2011-07-01  2200-01-01  index
000100.XSHG            上证F500  SZF500  2011-07-01  2200-01-01  index
000101.XSHG              5年信用    5NXY  2013-04-01  2200-01-01  index
000102.XSHG              沪投资品    HTZP  2011-06-13  2200-01-01  index
000103.XSHG              沪消费品    HXFP  2011-06-13  2200-01-01  index
000104.XSHG             380能源   380NY  2011-06-13  2200-01-01  index
000105.XSHG             380材料   380CL  2011-06-13  2200-01-01  index
000106.XSHG             380工业   380GY  2011-06-13  2200-01-01  index
000107.XSHG             380可选   380KX  2011-06-13  2200-01-01  index
000108.XSHG             380消费   380XF  2011-06-13  2200-01-01  index
000109.XSHG             380医药   380YY  2011-06-13  2200-01-01  index
000110.XSHG             380金融   380JR  2011-06-13  2200-01-01  index
000111.XSHG             380信息   380XX  2011-06-13  2200-01-01  index
000112.XSHG             380电信   380DX  2011-06-13  2200-01-01  index
000113.XSHG             380公用   380GY  2011-06-13  2200-01-01  index
000114.XSHG              持续产业    CXCY  2011-08-22  2200-01-01  index
000115.XSHG             380等权   380DQ  2011-08-12  2200-01-01  index
000116.XSHG             信用100   XY100  2013-02-26  2200-01-01  index
000117.XSHG             380成长   380CZ  2011-10-18  2200-01-01  index
000118.XSHG             380价值   380JZ  2011-10-18  2200-01-01  index
000119.XSHG            380R成长  380RCZ  2011-10-18  2200-01-01  index
000120.XSHG            380R价值  380RJZ  2011-10-18  2200-01-01  index
000121.XSHG              医药主题    YYZT  2011-10-18  2200-01-01  index
000122.XSHG              农业主题    NYZT  2011-10-18  2200-01-01  index
000123.XSHG             180动态   180DT  2013-02-08  2200-01-01  index
000125.XSHG             180稳定   180WD  2013-02-08  2200-01-01  index
000126.XSHG              消费50    XF50  2011-12-09  2200-01-01  index
000128.XSHG             380基本   380JB  2012-01-09  2200-01-01  index
000129.XSHG             180波动   180BD  2012-01-09  2200-01-01  index
000130.XSHG             380波动   380BD  2012-01-09  2200-01-01  index
000131.XSHG              上证高新    SZGX  2012-02-10  2200-01-01  index
000132.XSHG             上证100   SZ100  2012-04-20  2200-01-01  index
000133.XSHG             上证150   SZ150  2012-04-20  2200-01-01  index
000134.XSHG              上证银行    SZYH  2012-05-29  2200-01-01  index
000135.XSHG             180高贝   180GB  2012-08-06  2200-01-01  index
000136.XSHG             180低贝   180DB  2012-08-06  2200-01-01  index
000137.XSHG             380高贝   380GB  2012-08-06  2200-01-01  index
000138.XSHG             380低贝   380DB  2012-08-06  2200-01-01  index
000139.XSHG              上证转债    SZZZ  2012-09-12  2200-01-01  index
000141.XSHG             380动态   380DT  2013-02-08  2200-01-01  index
000142.XSHG             380稳定   380WD  2013-02-08  2200-01-01  index
000145.XSHG              优势资源    YSZY  2012-05-29  2200-01-01  index
000146.XSHG              优势制造    YSZZ  2012-05-29  2200-01-01  index
000147.XSHG              优势消费    YSXF  2012-05-29  2200-01-01  index
000148.XSHG              消费领先    XFLX  2012-05-29  2200-01-01  index
000149.XSHG             180红利   180HL  2012-07-20  2200-01-01  index
000150.XSHG             380红利   380HL  2012-07-20  2200-01-01  index
000151.XSHG              上国红利    SGHL  2012-07-20  2200-01-01  index
000152.XSHG              上央红利    SYHL  2012-07-20  2200-01-01  index
000153.XSHG              上民红利    SMHL  2012-07-20  2200-01-01  index
000155.XSHG              市值百强    SZBQ  2012-07-20  2200-01-01  index
000158.XSHG              上证环保    SZHB  2012-09-25  2200-01-01  index
000159.XSHG           上证沪股通指数     HGT  2014-11-17  2200-01-01  index
000160.XSHG        上证一带一路主题指数    HXSL  2015-06-24  2200-01-01  index
000161.XSHG    上证中国制造2025主题指数    HZGZ  2015-10-29  2200-01-01  index
000162.XSHG        上证互联网+主题指数    HHL+  2015-10-29  2200-01-01  index
000171.XSHG              新兴成指    XXCZ  2017-01-25  2020-12-28  index
000188.XSHG              中国波指    ZZBZ  2016-11-28  2018-02-14  index
000300.XSHG             沪深300   HS300  2005-04-08  2200-01-01  index
000688.XSHG              科创50    KC50  2020-07-23  2200-01-01  index
000801.XSHG              资源80    ZY80  2011-11-08  2020-04-22  index
000802.XSHG             500沪市   500HS  2011-11-08  2200-01-01  index
000803.XSHG             300波动   300BD  2012-01-09  2020-04-22  index
000804.XSHG             500波动   500BD  2012-01-09  2020-04-22  index
000805.XSHG              A股资源    AGZY  2012-01-06  2021-02-05  index
000806.XSHG              消费服务    XFFW  2012-02-10  2020-04-22  index
000807.XSHG              食品饮料    SPYL  2012-02-17  2020-04-22  index
000808.XSHG              医药生物    YYSW  2012-02-17  2021-02-05  index
000809.XSHG              细分农业    XFNY  2012-04-11  2020-04-22  index
000810.XSHG              细分能源    XFNY  2012-04-11  2020-04-22  index
000811.XSHG              细分有色    XFYS  2012-04-11  2020-04-22  index
000812.XSHG              细分机械    XFJX  2012-04-11  2020-04-22  index
000813.XSHG              细分化工    XFHG  2012-04-11  2020-04-22  index
000814.XSHG              细分医药    XFYY  2012-04-11  2200-01-01  index
000815.XSHG              细分食品    XFSP  2012-04-11  2020-04-22  index
000816.XSHG              细分地产    XFDC  2012-04-11  2020-04-22  index
000817.XSHG              兴证海峡    XZHX  2011-09-27  2018-04-11  index
000818.XSHG              细分金融    XFJR  2012-04-11  2020-04-22  index
000819.XSHG              有色金属    YSJS  2012-05-09  2200-01-01  index
000820.XSHG              煤炭指数    MTZS  2012-05-09  2020-04-22  index
000821.XSHG             300红利   300HL  2012-07-20  2020-04-22  index
000822.XSHG             500红利   500HL  2012-07-20  2020-04-22  index
000823.XSHG       中证800有色金属指数   800YS  2012-12-21  2200-01-01  index
000824.XSHG              国企红利    GQHL  2012-07-20  2020-04-22  index
000825.XSHG              央企红利    YQHL  2012-07-20  2020-04-22  index
000826.XSHG              民企红利    MQHL  2012-07-20  2020-04-22  index
000827.XSHG              中证环保    ZZHB  2012-09-25  2200-01-01  index
000828.XSHG             300高贝   300GB  2012-08-06  2021-02-05  index
000829.XSHG             300低贝   300DB  2012-08-06  2020-04-22  index
000830.XSHG             500高贝   500GB  2012-08-06  2020-04-22  index
000831.XSHG             500低贝   500DB  2012-08-06  2020-04-22  index
000832.XSHG              中证转债    ZZZZ  2012-09-12  2020-04-22  index
000833.XSHG              中高企债    ZGQZ  2012-09-10  2020-04-22  index
000838.XSHG              创业价值    CYJZ  2012-09-26  2020-04-22  index
000839.XSHG              浙企综指    ZQZZ  2012-11-09  2020-04-22  index
000840.XSHG              浙江民企    ZJMQ  2012-11-09  2020-04-22  index
000841.XSHG             800医药   800YY  2012-12-21  2021-02-05  index
000842.XSHG             800等权   800DQ  2012-12-21  2021-02-05  index
000843.XSHG             300动态   300DT  2013-01-07  2020-04-22  index
000844.XSHG             300稳定   300WD  2013-01-07  2020-04-22  index
000846.XSHG            ESG100  ESG100  2012-10-16  2020-04-22  index
000847.XSHG       中证腾安价值100指数    ZZTA  2013-11-18  2200-01-01  index
000849.XSHG      沪深300非银行金融指数   300FY  2012-12-21  2200-01-01  index
000850.XSHG       沪深300有色金属指数   300YS  2012-12-21  2018-12-25  index
000851.XSHG     中证百度百发策略100指数   BF100  2014-07-30  2200-01-01  index
000852.XSHG          中证1000指数  ZZ1000  2014-10-17  2200-01-01  index
000853.XSHG    中证申万一带一路主题投资指数  CSSWSL  2015-04-23  2200-01-01  index
000854.XSHG             500原料   500YL  2013-11-06  2200-01-01  index
000855.XSHG         央视财经500指数   YS500  2014-11-03  2200-01-01  index
000856.XSHG             500工业   500GY  2013-11-06  2200-01-01  index
000857.XSHG             500医药   500YY  2013-11-06  2200-01-01  index
000858.XSHG             500信息   500XX  2013-11-06  2200-01-01  index
000891.XSHG      中国战略新兴产业综合指数    XXZZ  2017-01-25  2200-01-01  index
000901.XSHG              小康指数    XKZS  2010-04-01  2200-01-01  index
000902.XSHG              中证流通    ZZLT  2006-02-27  2020-04-22  index
000903.XSHG             中证100   ZZ100  2006-05-29  2200-01-01  index
000904.XSHG             中证200   ZZ200  2007-01-15  2021-02-05  index
000905.XSHG             中证500   ZZ500  2007-01-15  2200-01-01  index
000906.XSHG             中证800   ZZ800  2007-01-15  2200-01-01  index
000907.XSHG             中证700   ZZ700  2007-01-15  2020-04-22  index
000908.XSHG             300能源   300NY  2007-07-02  2020-04-22  index
000909.XSHG             300材料   300CL  2007-07-02  2020-04-22  index
000910.XSHG             300工业   300GY  2007-07-02  2020-04-22  index
000911.XSHG             300可选   300KX  2007-07-02  2020-04-22  index
000912.XSHG             300消费   300XF  2007-07-02  2020-04-22  index
000913.XSHG             300医药   300YY  2007-07-02  2200-01-01  index
000914.XSHG             300金融   300JR  2007-07-02  2200-01-01  index
000915.XSHG             300信息   300XX  2007-07-02  2020-04-22  index
000916.XSHG             300电信   300DX  2007-07-02  2020-04-22  index
000917.XSHG             300公用   300GY  2007-07-02  2020-04-22  index
000918.XSHG             300成长   300CZ  2008-01-21  2021-02-05  index
000919.XSHG             300价值   300JZ  2008-01-21  2020-04-22  index
000920.XSHG            300R成长  300RCZ  2008-01-21  2020-04-22  index
000921.XSHG            300R价值  300RJZ  2008-01-21  2020-04-22  index
000922.XSHG              中证红利    ZZHL  2008-05-26  2020-04-22  index
000923.XSHG               公司债     GSZ  2008-11-19  2020-04-22  index
000925.XSHG             基本面50   JBM50  2009-02-26  2020-04-22  index
000926.XSHG              中证央企    ZZYQ  2009-03-30  2020-04-22  index
000927.XSHG             央企100   YQ100  2009-03-30  2020-04-22  index
000928.XSHG              中证能源    ZZNY  2009-07-03  2200-01-01  index
000929.XSHG              中证材料    ZZCL  2009-07-03  2020-04-22  index
000930.XSHG              中证工业    ZZGY  2009-07-03  2020-04-22  index
000931.XSHG              中证可选    ZZKX  2009-07-03  2020-04-22  index
000932.XSHG              中证消费    ZZXF  2009-07-03  2200-01-01  index
000933.XSHG              中证医药    ZZYY  2009-07-03  2200-01-01  index
000934.XSHG              中证金融    ZZJR  2009-07-03  2200-01-01  index
000935.XSHG              中证信息    ZZXX  2009-07-03  2200-01-01  index
000936.XSHG              中证电信    ZZDX  2009-07-03  2020-04-22  index
000937.XSHG              中证公用    ZZGY  2009-07-03  2020-04-22  index
000938.XSHG              中证民企    ZZMQ  2009-08-25  2020-04-22  index
000939.XSHG             民企200   MQ200  2009-08-25  2020-04-22  index
000940.XSHG              财富大盘    CFDP  2009-09-25  2021-02-05  index
000941.XSHG               新能源     XNY  2009-10-28  2020-04-22  index
000942.XSHG              内地消费    NDXF  2009-10-28  2020-04-22  index
000943.XSHG              内地基建    NDJJ  2009-10-28  2020-04-22  index
000944.XSHG              内地资源    NDZY  2009-10-28  2021-02-05  index
000945.XSHG              内地运输    NDYS  2009-10-28  2020-04-22  index
000946.XSHG              内地金融    NDJR  2009-10-28  2020-04-22  index
000947.XSHG              内地银行    NDYH  2009-10-28  2020-04-22  index
000948.XSHG              内地地产    NDDC  2009-10-28  2020-04-22  index
000949.XSHG              内地农业    NDNY  2009-10-28  2020-04-22  index
000950.XSHG             300基建   300JJ  2009-10-28  2020-04-22  index
000951.XSHG             300银行   300YH  2009-10-28  2020-04-22  index
000952.XSHG             300地产   300DC  2009-10-28  2020-04-22  index
000953.XSHG              中证地企    ZZDQ  2010-02-09  2020-04-22  index
000954.XSHG             地企100   DQ100  2010-02-09  2020-04-22  index
000955.XSHG              中证国企    ZZGQ  2010-02-09  2020-04-22  index
000956.XSHG             国企200   GQ200  2010-02-09  2020-04-22  index
000957.XSHG             300运输   300YS  2009-06-16  2020-04-22  index
000958.XSHG              创业成长    CYCZ  2010-03-24  2021-02-05  index
000959.XSHG              银河99    YH99  2010-02-09  2020-04-22  index
000960.XSHG              中证龙头    ZZLT  2010-02-09  2020-04-22  index
000961.XSHG              中证上游    ZZSY  2010-04-16  2020-04-22  index
000962.XSHG              中证中游    ZZZY  2010-04-16  2020-04-22  index
000963.XSHG              中证下游    ZZXY  2010-04-16  2020-04-22  index
000964.XSHG              中证新兴    ZZXX  2010-04-30  2020-04-22  index
000965.XSHG             基本200   JB200  2010-06-02  2020-04-22  index
000966.XSHG             基本400   JB400  2010-06-02  2021-02-05  index
000967.XSHG             基本600   JB600  2010-06-02  2020-04-22  index
000968.XSHG             300周期   300ZQ  2010-05-28  2020-04-22  index
000969.XSHG             300非周   300FZ  2010-05-28  2020-04-22  index
000970.XSHG             ESG40   ESG40  2010-09-17  2020-04-22  index
000971.XSHG              等权90    DQ90  2010-12-02  2021-02-05  index
000972.XSHG             300沪市   300HS  2010-12-02  2020-04-22  index
000973.XSHG              技术领先    JSLX  2011-01-04  2018-02-02  index
000974.XSHG         中证800金融指数   800JR  2013-05-09  2200-01-01  index
000975.XSHG              钱江30    QJ30  2014-01-02  2020-04-22  index
000976.XSHG              新华金牛    XHJN  2014-02-18  2017-04-10  index
000977.XSHG              内地低碳    NDDT  2011-01-21  2020-04-22  index
000978.XSHG             医药100   YY100  2011-03-18  2020-04-22  index
000979.XSHG              大宗商品    DZSP  2011-08-22  2020-04-22  index
000980.XSHG              中证超大    ZZCD  2011-05-10  2020-04-22  index
000981.XSHG             300分层   300FC  2011-06-13  2020-04-22  index
000982.XSHG             500等权   500DQ  2011-06-13  2200-01-01  index
000983.XSHG              智能资产    ZNZC  2011-06-17  2020-04-22  index
000984.XSHG             300等权   300DQ  2011-08-02  2021-02-05  index
000985.XSHG              中证全指    ZZQZ  2011-08-02  2020-04-22  index
000986.XSHG              全指能源    QZNY  2011-08-02  2200-01-01  index
000987.XSHG              全指材料    QZCL  2011-08-02  2200-01-01  index
000988.XSHG              全指工业    QZGY  2011-08-02  2020-04-22  index
000989.XSHG              全指可选    QZKX  2011-08-02  2200-01-01  index
000990.XSHG              全指消费    QZXF  2011-08-02  2021-02-05  index
000991.XSHG              全指医药    QZYY  2011-08-02  2200-01-01  index

In [ ]:
dfu = df1[df1['end_date']!='2200-01-01']

print('all {}, u {}'.format(len(df1),len(dfu)))

In [7]:
dfcc = df1[df1['end_date']=='2200-01-01']
dfcc

                 display_name    name  start_date    end_date   type
000001.XSHG              上证指数    SZZS  1991-07-15  2200-01-01  index
000002.XSHG              A股指数    AGZS  1992-02-21  2200-01-01  index
000003.XSHG              B股指数    BGZS  1992-02-21  2200-01-01  index
000004.XSHG              工业指数    GYZS  1993-05-03  2200-01-01  index
000005.XSHG              商业指数    SYZS  1993-05-03  2200-01-01  index
000006.XSHG              地产指数    DCZS  1993-05-03  2200-01-01  index
000007.XSHG              公用指数    GYZS  1993-05-03  2200-01-01  index
000008.XSHG              综合指数    ZHZS  1993-05-03  2200-01-01  index
000009.XSHG             上证380   SZ380  2010-11-29  2200-01-01  index
000010.XSHG             上证180   SZ180  2002-07-01  2200-01-01  index
000011.XSHG              基金指数    JJZS  2000-06-09  2200-01-01  index
000012.XSHG              国债指数    GZZS  2003-01-02  2200-01-01  index
000015.XSHG              红利指数    HLZS  2005-01-04  2200-01-01  index
000016.XSHG              上证50    SZ50  2004-01-02  2200-01-01  index
000017.XSHG               新综指     XZZ  2006-01-04  2200-01-01  index
000018.XSHG             180金融   180JR  2007-12-10  2200-01-01  index
000019.XSHG              治理指数    ZLZS  2008-01-02  2200-01-01  index
000020.XSHG              中型综指    ZXZZ  2008-05-12  2200-01-01  index
000021.XSHG             180治理   180ZL  2008-09-10  2200-01-01  index
000022.XSHG           上证公司债指数    HGSZ  2008-11-19  2200-01-01  index
000025.XSHG             180基建   180JJ  2008-12-15  2200-01-01  index
000026.XSHG             180资源   180ZY  2008-12-15  2200-01-01  index
000027.XSHG             180运输   180YS  2008-12-15  2200-01-01  index
000028.XSHG             180成长   180CZ  2009-01-09  2200-01-01  index
000029.XSHG             180价值   180JZ  2009-01-09  2200-01-01  index
000030.XSHG            180R成长  180RCZ  2009-01-09  2200-01-01  index
000031.XSHG            180R价值  180RJZ  2009-01-09  2200-01-01  index
000032.XSHG              上证能源    SZNY  2009-01-09  2200-01-01  index
000033.XSHG              上证材料    SZCL  2009-01-09  2200-01-01  index
000034.XSHG              上证工业    SZGY  2009-01-09  2200-01-01  index
000035.XSHG              上证可选    SZKX  2009-01-09  2200-01-01  index
000036.XSHG              上证消费    SZXF  2009-01-09  2200-01-01  index
000037.XSHG              上证医药    SZYY  2009-01-09  2200-01-01  index
000038.XSHG              上证金融    SZJR  2009-01-09  2200-01-01  index
000039.XSHG              上证信息    SZXX  2009-01-09  2200-01-01  index
000040.XSHG              上证电信    SZDX  2009-01-09  2200-01-01  index
000041.XSHG              上证公用    SZGY  2009-01-09  2200-01-01  index
000042.XSHG              上证央企    SZYQ  2009-03-30  2200-01-01  index
000043.XSHG               超大盘     CDP  2009-04-23  2200-01-01  index
000044.XSHG              上证中盘    SZZP  2009-07-03  2200-01-01  index
000045.XSHG              上证小盘    SZXP  2009-07-03  2200-01-01  index
000046.XSHG              上证中小    SZZX  2009-07-03  2200-01-01  index
000047.XSHG              上证全指    SZQZ  2009-07-03  2200-01-01  index
000048.XSHG              责任指数    ZRZS  2009-08-05  2200-01-01  index
000049.XSHG              上证民企    SZMQ  2009-08-25  2200-01-01  index
000050.XSHG              50等权    50DQ  2011-01-04  2200-01-01  index
000051.XSHG             180等权   180DQ  2011-05-24  2200-01-01  index
000052.XSHG              50基本    50JB  2012-01-09  2200-01-01  index
000053.XSHG             180基本   180JB  2012-01-09  2200-01-01  index
000054.XSHG              上证海外    SZHW  2010-01-04  2200-01-01  index
000055.XSHG              上证地企    SZDQ  2010-01-04  2200-01-01  index
000056.XSHG              上证国企    SZGQ  2010-01-04  2200-01-01  index
000057.XSHG              全指成长    QZCZ  2010-01-04  2200-01-01  index
000058.XSHG              全指价值    QZJZ  2010-01-04  2200-01-01  index
000059.XSHG              全R成长    QRCZ  2010-01-04  2200-01-01  index
000060.XSHG              全R价值    QRJZ  2010-01-04  2200-01-01  index
000061.XSHG             沪企债30   HQZ30  2010-01-04  2200-01-01  index
000062.XSHG              上证沪企    SZHQ  2010-01-04  2200-01-01  index
000063.XSHG              上证周期    SZZQ  2010-02-03  2200-01-01  index
000064.XSHG               非周期     FZQ  2010-02-03  2200-01-01  index
000065.XSHG              上证龙头    SZLT  2010-02-09  2200-01-01  index
000066.XSHG              上证商品    SZSP  2010-04-30  2200-01-01  index
000067.XSHG              上证新兴    SZXX  2010-04-30  2200-01-01  index
000068.XSHG              上证资源    SZZY  2010-05-28  2200-01-01  index
000069.XSHG              消费80    XF80  2010-05-28  2200-01-01  index
000070.XSHG              能源等权    NYDQ  2010-08-18  2200-01-01  index
000071.XSHG              材料等权    CLDQ  2010-08-18  2200-01-01  index
000072.XSHG              工业等权    GYDQ  2010-08-18  2200-01-01  index
000073.XSHG              可选等权    KXDQ  2010-08-18  2200-01-01  index
000074.XSHG              消费等权    XFDQ  2010-08-18  2200-01-01  index
000075.XSHG              医药等权    YYDQ  2010-08-18  2200-01-01  index
000076.XSHG              金融等权    JRDQ  2010-08-18  2200-01-01  index
000077.XSHG              信息等权    XXDQ  2010-08-18  2200-01-01  index
000078.XSHG              电信等权    DXDQ  2010-08-18  2200-01-01  index
000079.XSHG              公用等权    GYDQ  2010-08-18  2200-01-01  index
000090.XSHG              上证流通    SZLT  2010-12-02  2200-01-01  index
000091.XSHG              沪财中小    HCZX  2011-04-06  2200-01-01  index
000092.XSHG              资源50    ZY50  2011-05-10  2200-01-01  index
000093.XSHG             180分层   180FC  2011-05-24  2200-01-01  index
000094.XSHG              上证上游    SZSY  2011-05-10  2200-01-01  index
000095.XSHG              上证中游    SZZY  2011-05-10  2200-01-01  index
000096.XSHG              上证下游    SZXY  2011-05-10  2200-01-01  index
000097.XSHG              高端装备    GDZB  2011-05-24  2200-01-01  index
000098.XSHG            上证F200  SZF200  2011-07-01  2200-01-01  index
000099.XSHG            上证F300  SZF300  2011-07-01  2200-01-01  index
000100.XSHG            上证F500  SZF500  2011-07-01  2200-01-01  index
000101.XSHG              5年信用    5NXY  2013-04-01  2200-01-01  index
000102.XSHG              沪投资品    HTZP  2011-06-13  2200-01-01  index
000103.XSHG              沪消费品    HXFP  2011-06-13  2200-01-01  index
000104.XSHG             380能源   380NY  2011-06-13  2200-01-01  index
000105.XSHG             380材料   380CL  2011-06-13  2200-01-01  index
000106.XSHG             380工业   380GY  2011-06-13  2200-01-01  index
000107.XSHG             380可选   380KX  2011-06-13  2200-01-01  index
000108.XSHG             380消费   380XF  2011-06-13  2200-01-01  index
000109.XSHG             380医药   380YY  2011-06-13  2200-01-01  index
000110.XSHG             380金融   380JR  2011-06-13  2200-01-01  index
000111.XSHG             380信息   380XX  2011-06-13  2200-01-01  index
000112.XSHG             380电信   380DX  2011-06-13  2200-01-01  index
000113.XSHG             380公用   380GY  2011-06-13  2200-01-01  index
000114.XSHG              持续产业    CXCY  2011-08-22  2200-01-01  index
000115.XSHG             380等权   380DQ  2011-08-12  2200-01-01  index
000116.XSHG             信用100   XY100  2013-02-26  2200-01-01  index
000117.XSHG             380成长   380CZ  2011-10-18  2200-01-01  index
000118.XSHG             380价值   380JZ  2011-10-18  2200-01-01  index
000119.XSHG            380R成长  380RCZ  2011-10-18  2200-01-01  index
000120.XSHG            380R价值  380RJZ  2011-10-18  2200-01-01  index
000121.XSHG              医药主题    YYZT  2011-10-18  2200-01-01  index
000122.XSHG              农业主题    NYZT  2011-10-18  2200-01-01  index
000123.XSHG             180动态   180DT  2013-02-08  2200-01-01  index
000125.XSHG             180稳定   180WD  2013-02-08  2200-01-01  index
000126.XSHG              消费50    XF50  2011-12-09  2200-01-01  index
000128.XSHG             380基本   380JB  2012-01-09  2200-01-01  index
000129.XSHG             180波动   180BD  2012-01-09  2200-01-01  index
000130.XSHG             380波动   380BD  2012-01-09  2200-01-01  index
000131.XSHG              上证高新    SZGX  2012-02-10  2200-01-01  index
000132.XSHG             上证100   SZ100  2012-04-20  2200-01-01  index
000133.XSHG             上证150   SZ150  2012-04-20  2200-01-01  index
000134.XSHG              上证银行    SZYH  2012-05-29  2200-01-01  index
000135.XSHG             180高贝   180GB  2012-08-06  2200-01-01  index
000136.XSHG             180低贝   180DB  2012-08-06  2200-01-01  index
000137.XSHG             380高贝   380GB  2012-08-06  2200-01-01  index
000138.XSHG             380低贝   380DB  2012-08-06  2200-01-01  index
000139.XSHG              上证转债    SZZZ  2012-09-12  2200-01-01  index
000141.XSHG             380动态   380DT  2013-02-08  2200-01-01  index
000142.XSHG             380稳定   380WD  2013-02-08  2200-01-01  index
000145.XSHG              优势资源    YSZY  2012-05-29  2200-01-01  index
000146.XSHG              优势制造    YSZZ  2012-05-29  2200-01-01  index
000147.XSHG              优势消费    YSXF  2012-05-29  2200-01-01  index
000148.XSHG              消费领先    XFLX  2012-05-29  2200-01-01  index
000149.XSHG             180红利   180HL  2012-07-20  2200-01-01  index
000150.XSHG             380红利   380HL  2012-07-20  2200-01-01  index
000151.XSHG              上国红利    SGHL  2012-07-20  2200-01-01  index
000152.XSHG              上央红利    SYHL  2012-07-20  2200-01-01  index
000153.XSHG              上民红利    SMHL  2012-07-20  2200-01-01  index
000155.XSHG              市值百强    SZBQ  2012-07-20  2200-01-01  index
000158.XSHG              上证环保    SZHB  2012-09-25  2200-01-01  index
000159.XSHG           上证沪股通指数     HGT  2014-11-17  2200-01-01  index
000160.XSHG        上证一带一路主题指数    HXSL  2015-06-24  2200-01-01  index
000161.XSHG    上证中国制造2025主题指数    HZGZ  2015-10-29  2200-01-01  index
000162.XSHG        上证互联网+主题指数    HHL+  2015-10-29  2200-01-01  index
000300.XSHG             沪深300   HS300  2005-04-08  2200-01-01  index
000688.XSHG              科创50    KC50  2020-07-23  2200-01-01  index
000802.XSHG             500沪市   500HS  2011-11-08  2200-01-01  index
000814.XSHG              细分医药    XFYY  2012-04-11  2200-01-01  index
000819.XSHG              有色金属    YSJS  2012-05-09  2200-01-01  index
000823.XSHG       中证800有色金属指数   800YS  2012-12-21  2200-01-01  index
000827.XSHG              中证环保    ZZHB  2012-09-25  2200-01-01  index
000847.XSHG       中证腾安价值100指数    ZZTA  2013-11-18  2200-01-01  index
000849.XSHG      沪深300非银行金融指数   300FY  2012-12-21  2200-01-01  index
000851.XSHG     中证百度百发策略100指数   BF100  2014-07-30  2200-01-01  index
000852.XSHG          中证1000指数  ZZ1000  2014-10-17  2200-01-01  index
000853.XSHG    中证申万一带一路主题投资指数  CSSWSL  2015-04-23  2200-01-01  index
000854.XSHG             500原料   500YL  2013-11-06  2200-01-01  index
000855.XSHG         央视财经500指数   YS500  2014-11-03  2200-01-01  index
000856.XSHG             500工业   500GY  2013-11-06  2200-01-01  index
000857.XSHG             500医药   500YY  2013-11-06  2200-01-01  index
000858.XSHG             500信息   500XX  2013-11-06  2200-01-01  index
000891.XSHG      中国战略新兴产业综合指数    XXZZ  2017-01-25  2200-01-01  index
000901.XSHG              小康指数    XKZS  2010-04-01  2200-01-01  index
000903.XSHG             中证100   ZZ100  2006-05-29  2200-01-01  index
000905.XSHG             中证500   ZZ500  2007-01-15  2200-01-01  index
000906.XSHG             中证800   ZZ800  2007-01-15  2200-01-01  index
000913.XSHG             300医药   300YY  2007-07-02  2200-01-01  index
000914.XSHG             300金融   300JR  2007-07-02  2200-01-01  index
000928.XSHG              中证能源    ZZNY  2009-07-03  2200-01-01  index
000932.XSHG              中证消费    ZZXF  2009-07-03  2200-01-01  index
000933.XSHG              中证医药    ZZYY  2009-07-03  2200-01-01  index
000934.XSHG              中证金融    ZZJR  2009-07-03  2200-01-01  index
000935.XSHG              中证信息    ZZXX  2009-07-03  2200-01-01  index
000974.XSHG         中证800金融指数   800JR  2013-05-09  2200-01-01  index
000982.XSHG             500等权   500DQ  2011-06-13  2200-01-01  index
000986.XSHG              全指能源    QZNY  2011-08-02  2200-01-01  index
000987.XSHG              全指材料    QZCL  2011-08-02  2200-01-01  index
000989.XSHG              全指可选    QZKX  2011-08-02  2200-01-01  index
000991.XSHG              全指医药    QZYY  2011-08-02  2200-01-01  index
000992.XSHG              全指金融    QZJR  2011-08-02  2200-01-01  index
000993.XSHG              全指信息    QZXX  2011-08-02  2200-01-01  index
399001.XSHE              深证成指    SZCZ  1995-01-23  2200-01-01  index
399002.XSHE              深成指R    SCZR  1995-01-23  2200-01-01  index
399003.XSHE              成份B指    CFBZ  1995-01-23  2200-01-01  index
399004.XSHE            深证100R  SZ100R  2003-01-02  2200-01-01  index
399005.XSHE              中小板指    ZXBZ  2006-01-24  2200-01-01  index
399006.XSHE              创业板指    CYBZ  2010-06-01  2200-01-01  index
399007.XSHE             深证300   SZ300  2009-11-04  2200-01-01  index
399008.XSHE             中小300   ZX300  2010-03-22  2200-01-01  index
399009.XSHE             深证200   SZ200  2011-09-01  2200-01-01  index
399010.XSHE             深证700   SZ700  2011-09-01  2200-01-01  index
399011.XSHE            深证1000  SZ1000  2011-09-01  2200-01-01  index
399012.XSHE             创业300   CY300  2013-01-07  2200-01-01  index
399013.XSHE              深市精选    SSJX  2014-05-30  2200-01-01  index
399015.XSHE          深证中小创新指数    ZXCX  2015-03-24  2200-01-01  index
399016.XSHE            深证创新指数    SZCX  2016-12-01  2200-01-01  index
399017.XSHE           中小板创新指数   SMECX  2016-12-01  2200-01-01  index
399018.XSHE           创业板创新指数    CYCX  2016-12-01  2200-01-01  index
399050.XSHE              创新引擎    CXYQ  2018-07-31  2200-01-01  index
399088.XSHE             深创100   SC100  2020-02-18  2200-01-01  index
399100.XSHE               新指数     XZS  2006-02-16  2200-01-01  index
399101.XSHE              中小板综    ZXBZ  2005-12-01  2200-01-01  index
399102.XSHE           创业板综合指数    CYBZ  2010-08-20  2200-01-01  index
399103.XSHE              乐富指数    LFZS  2011-12-02  2200-01-01  index
399106.XSHE              深证综指    SZZZ  1991-04-04  2200-01-01  index
399107.XSHE              深证A指    SZAZ  1992-10-04  2200-01-01  index
399108.XSHE              深证B指    SZBZ  1992-10-06  2200-01-01  index
399231.XSHE              农林指数    NLZS  2013-03-04  2200-01-01  index
399232.XSHE              采矿指数    CKZS  2013-03-04  2200-01-01  index
399233.XSHE              制造指数    ZZZS  2013-03-04  2200-01-01  index
399234.XSHE              水电指数    SDZS  2013-03-04  2200-01-01  index
399235.XSHE              建筑指数    JZZS  2013-03-04  2200-01-01  index
399236.XSHE              批零指数    PLZS  2013-03-04  2200-01-01  index
399237.XSHE              运输指数    YSZS  2013-03-04  2200-01-01  index
399238.XSHE              餐饮指数    CYZS  2013-03-04  2200-01-01  index
399239.XSHE              IT指数    ITZS  2013-03-04  2200-01-01  index
399240.XSHE              金融指数    JRZS  2013-03-04  2200-01-01  index
399241.XSHE              地产指数    DCZS  2013-03-04  2200-01-01  index
399242.XSHE              商务指数    SWZS  2013-03-04  2200-01-01  index
399243.XSHE              科研指数    KYZS  2013-03-04  2200-01-01  index
399244.XSHE              公共指数    GGZS  2013-03-04  2200-01-01  index
399248.XSHE              文化指数    WHZS  2013-03-04  2200-01-01  index
399249.XSHE              综企指数    ZQZS  2013-03-04  2200-01-01  index
399269.XSHE               创质量     CZL  2021-01-12  2200-01-01  index
399275.XSHE               创医药     CYY  2020-10-26  2200-01-01  index
399276.XSHE               创科技     CKJ  2020-10-26  2200-01-01  index
399277.XSHE              公共健康    GGJK  2020-05-08  2200-01-01  index
399278.XSHE             长江100   CJ100  2020-05-08  2200-01-01  index
399279.XSHE             云科技50   YKJ50  2020-05-08  2200-01-01  index
399280.XSHE              生物50    SW50  2020-05-08  2200-01-01  index
399281.XSHE              电子50    DZ50  2020-05-08  2200-01-01  index
399282.XSHE             大数据50   DSJ50  2020-02-18  2200-01-01  index
399283.XSHE             机器人50   JQR50  2020-02-18  2200-01-01  index
399284.XSHE             AI 50   AI 50  2020-02-18  2200-01-01  index
399285.XSHE             物联网50   WLW50  2020-02-18  2200-01-01  index
399286.XSHE             区块链50   QKL50  2019-12-23  2200-01-01  index
399290.XSHE              深转交债    SZJZ  2019-06-06  2200-01-01  index
399291.XSHE             创精选88   CJX88  2019-11-06  2200-01-01  index
399292.XSHE              民企发展    MQFZ  2019-03-05  2200-01-01  index
399293.XSHE              创业大盘    CYDP  2019-04-18  2200-01-01  index
399294.XSHE              中小创Q    ZXCQ  2019-06-06  2200-01-01  index
399295.XSHE              创业蓝筹    CYLC  2019-01-23  2200-01-01  index
399296.XSHE               创成长     CCC  2019-01-23  2200-01-01  index
399298.XSHE       深证中高等级信用债指数    SXZG  2014-09-25  2200-01-01  index
399299.XSHE       深证中低等级信用债指数    SXZD  2014-09-25  2200-01-01  index
399300.XSHE             沪深300   HS300  2005-04-08  2200-01-01  index
399301.XSHE              深信用债    SXYZ  2013-01-11  2200-01-01  index
399302.XSHE              深公司债    SGSZ  2013-01-11  2200-01-01  index
399303.XSHE            国证2000  GZ2000  2014-03-28  2200-01-01  index
399306.XSHE             深证ETF   SZETF  2011-12-02  2200-01-01  index
399307.XSHE              深证转债    SZZZ  2014-08-27  2200-01-01  index
399310.XSHE              国证50    GZ50  2005-09-05  2200-01-01  index
399311.XSHE            国证1000  GZ1000  2005-02-03  2200-01-01  index
399312.XSHE             国证300   GZ300  2005-02-03  2200-01-01  index
399313.XSHE             巨潮100   JC100  2005-02-03  2200-01-01  index
399314.XSHE              巨潮大盘    JCDP  2005-02-03  2200-01-01  index
399315.XSHE              巨潮中盘    JCZP  2005-02-03  2200-01-01  index
399316.XSHE              巨潮小盘    JCXP  2005-02-03  2200-01-01  index
399317.XSHE              国证A指    GZAZ  2005-02-03  2200-01-01  index
399318.XSHE            巨潮B股指数    JCBZ  2005-02-03  2200-01-01  index
399319.XSHE              资源优势    ZYYS  2005-01-04  2200-01-01  index
399320.XSHE              国证服务    GZFW  2005-01-04  2200-01-01  index
399321.XSHE              国证红利    GZHL  2005-01-04  2200-01-01  index
399322.XSHE              国证治理    GZZL  2005-12-12  2200-01-01  index
399324.XSHE              深证红利    SZHL  2006-01-24  2200-01-01  index
399326.XSHE              成长40    CZ40  2006-01-24  2200-01-01  index
399328.XSHE              深证治理    SZZL  2006-01-24  2200-01-01  index
399330.XSHE             深证100   SZ100  2006-01-24  2200-01-01  index
399333.XSHE              中小板R    ZXBR  2006-12-27  2200-01-01  index
399335.XSHE              深证央企    SZYQ  2009-08-03  2200-01-01  index
399337.XSHE              深证民营    SZMY  2009-08-03  2200-01-01  index
399339.XSHE              深证科技    SZKJ  2009-08-03  2200-01-01  index
399341.XSHE              深证责任    SZZR  2009-08-03  2200-01-01  index
399344.XSHE            深证300R  SZ300R  2009-11-04  2200-01-01  index
399346.XSHE              深证成长    SZCZ  2009-11-04  2200-01-01  index
399348.XSHE              深证价值    SZJZ  2009-11-04  2200-01-01  index
399350.XSHE              皖江30    WJ30  2012-12-18  2200-01-01  index
399351.XSHE              深报指数    SBZS  2004-09-01  2200-01-01  index
399352.XSHE              深报综指    SBZZ  2005-02-03  2200-01-01  index
399353.XSHE              国证物流    GZWL  2005-03-01  2200-01-01  index
399354.XSHE             分析师指数   FXSZS  2006-11-25  2200-01-01  index
399355.XSHE               长三角     ZSJ  2007-07-02  2200-01-01  index
399356.XSHE               珠三角     ZSJ  2007-07-02  2200-01-01  index
399357.XSHE               环渤海     HBH  2007-07-02  2200-01-01  index
399358.XSHE              泰达指数    TDZS  2008-01-02  2200-01-01  index
399359.XSHE              国证基建    GZJJ  2009-08-03  2200-01-01  index
399360.XSHE              国证装备    GZZB  2009-08-03  2200-01-01  index
399361.XSHE              国证商业    GZSY  2009-08-03  2200-01-01  index
399362.XSHE              国证民营    GZMY  2009-08-03  2200-01-01  index
399363.XSHE              计算机指    JSJZ  2009-08-03  2200-01-01  index
399364.XSHE              中金消费    ZJXF  2009-08-03  2200-01-01  index
399365.XSHE              国证农业    GZNY  2009-11-04  2200-01-01  index

In [5]:
df2 = pd.read_csv('./csv_files/etf.csv', parse_dates=True, index_col=0)

df2

            display_name        name  start_date    end_date type
159001.XSHE          保证金         BZJ  2014-10-20  2200-01-01  etf
159003.XSHE         招商快线        ZSKX  2014-10-20  2200-01-01  etf
159005.XSHE         添富快钱        TFKQ  2015-01-13  2200-01-01  etf
159702.XSHE        AIETF       AIETF  2021-05-18  2200-01-01  etf
159703.XSHE          新材料         XCL  2021-06-08  2200-01-01  etf
159735.XSHE         港股消费        GGXF  2021-06-04  2200-01-01  etf
159740.XSHE         恒生科技        HSKJ  2021-05-27  2200-01-01  etf
159741.XSHE         港股科技        GGKJ  2021-06-03  2200-01-01  etf
159742.XSHE         恒指科技        HZKJ  2021-05-25  2200-01-01  etf
159801.XSHE         芯片基金        XPJJ  2020-02-18  2200-01-01  etf
159802.XSHE       800ETF      800ETF  2020-05-15  2020-09-22  etf
159803.XSHE        浙江ETF       ZJETF  2020-05-26  2200-01-01  etf
159804.XSHE        创精选88       CJX88  2020-03-31  2200-01-01  etf
159805.XSHE        传媒ETF       CMETF  2020-04-17  2200-01-01  etf
159806.XSHE          新能车         XNC  2020-03-20  2200-01-01  etf
159807.XSHE         科技50       KJETF  2020-03-30  2200-01-01  etf
159808.XSHE        创业板RT       CYBRT  2020-09-04  2200-01-01  etf
159809.XSHE         恒生湾区        HSWQ  2020-05-21  2200-01-01  etf
159810.XSHE         浦银创业        PYCY  2020-07-10  2200-01-01  etf
159811.XSHE      5G50ETF     5G50ETF  2020-04-22  2200-01-01  etf
159812.XSHE         黄金基金        HJJJ  2020-05-29  2200-01-01  etf
159813.XSHE           芯片          XP  2020-05-25  2200-01-01  etf
159814.XSHE         创业大盘        CYDP  2020-07-17  2200-01-01  etf
159815.XSHE        浙江100       ZJ100  2020-08-18  2200-01-01  etf
159816.XSHE        0-4地债       0-4DZ  2020-09-04  2200-01-01  etf
159819.XSHE         AI智能        AIZN  2020-09-23  2200-01-01  etf
159820.XSHE      500ETF基     500ETFJ  2020-08-24  2200-01-01  etf
159821.XSHE       BOCI创业      BOCICY  2020-10-29  2200-01-01  etf
159822.XSHE          新经济         XJJ  2020-10-23  2200-01-01  etf
159823.XSHE      H股50ETF     HG50ETF  2020-10-23  2200-01-01  etf
159824.XSHE         新能汽车        XNQC  2021-01-11  2200-01-01  etf
159825.XSHE        农业ETF       NYETF  2020-12-29  2200-01-01  etf
159827.XSHE         农业50        NY50  2020-12-18  2200-01-01  etf
159828.XSHE        医疗ETF       YLETF  2021-01-12  2200-01-01  etf
159835.XSHE         创新药业        CXYY  2021-03-29  2200-01-01  etf
159836.XSHE      创300ETF     C300ETF  2021-05-25  2200-01-01  etf
159837.XSHE         生物科技        SWKJ  2021-01-27  2200-01-01  etf
159839.XSHE          生物药         SWY  2021-02-22  2200-01-01  etf
159841.XSHE        证券ETF       ZQETF  2021-02-09  2200-01-01  etf
159842.XSHE        券商ETF       QSETF  2021-03-19  2200-01-01  etf
159843.XSHE         食品饮料        SPYL  2021-02-05  2200-01-01  etf
159845.XSHE       中证1000      ZZ1000  2021-03-31  2200-01-01  etf
159848.XSHE         证券公司        ZQGS  2021-03-12  2200-01-01  etf
159849.XSHE        生物ETF       SWETF  2021-03-02  2200-01-01  etf
159850.XSHE         H股50        HG50  2021-02-19  2200-01-01  etf
159851.XSHE        金科ETF       JKETF  2021-03-19  2200-01-01  etf
159852.XSHE        软件ETF       RJETF  2021-02-09  2200-01-01  etf
159855.XSHE        影视ETF       YSETF  2021-02-26  2200-01-01  etf
159856.XSHE        互联网50       HLW50  2021-02-01  2200-01-01  etf
159857.XSHE        光伏ETF       GFETF  2021-02-24  2200-01-01  etf
159858.XSHE         创新药指        CXYZ  2021-03-25  2200-01-01  etf
159861.XSHE        环保ETF       HBETF  2021-04-02  2200-01-01  etf
159863.XSHE         光伏产业        GFCY  2021-03-11  2200-01-01  etf
159865.XSHE        养殖ETF       YZETF  2021-03-08  2200-01-01  etf
159866.XSHE        日经ETF       RJETF  2021-04-08  2200-01-01  etf
159867.XSHE        畜牧ETF       XMETF  2021-03-05  2200-01-01  etf
159869.XSHE        游戏ETF       YXETF  2021-03-05  2200-01-01  etf
159870.XSHE        化工ETF       HGETF  2021-03-03  2200-01-01  etf
159871.XSHE         有色金属        YSJS  2021-03-31  2200-01-01  etf
159873.XSHE         医疗设备        YLSB  2021-03-29  2200-01-01  etf
159876.XSHE           有色          YS  2021-03-24  2200-01-01  etf
159880.XSHE         有色50        YS50  2021-03-25  2200-01-01  etf
159883.XSHE         医疗器械        YLQX  2021-04-30  2200-01-01  etf
159885.XSHE        低碳ETF       DTETF  2021-04-14  2200-01-01  etf
159886.XSHE        机械ETF       JXETF  2021-04-28  2200-01-01  etf
159887.XSHE        银行ETF       YHETF  2021-05-20  2200-01-01  etf
159888.XSHE          智能车         ZNC  2021-05-21  2200-01-01  etf
159890.XSHE         云ETF        YETF  2021-04-02  2200-01-01  etf
159891.XSHE           医疗          YL  2021-06-15  2200-01-01  etf
159898.XSHE        器械ETF       QXETF  2021-06-04  2200-01-01  etf
159901.XSHE      深100ETF     S100ETF  2006-04-24  2200-01-01  etf
159902.XSHE        中小100         ZXB  2006-09-05  2200-01-01  etf
159903.XSHE        深成ETF       SCETF  2010-02-02  2200-01-01  etf
159905.XSHE          深红利         SHL  2011-01-11  2200-01-01  etf
159906.XSHE          深成长         SCZ  2011-02-23  2200-01-01  etf
159907.XSHE        中小300       ZX300  2011-08-10  2200-01-01  etf
159908.XSHE        创业板BS       SF200  2011-07-13  2200-01-01  etf
159909.XSHE         深TMT        STMT  2011-09-01  2200-01-01  etf
159910.XSHE        深F120       SF120  2011-09-27  2200-01-01  etf
159911.XSHE        民营ETF       MYETF  2011-10-14  2020-06-18  etf
159912.XSHE      深300ETF     S300ETF  2011-11-24  2200-01-01  etf
159913.XSHE          深价值         SJZ  2011-10-25  2200-01-01  etf
159915.XSHE          创业板         CYB  2011-12-09  2200-01-01  etf
159916.XSHE         深F60        SF60  2011-10-24  2200-01-01  etf
159918.XSHE        中创400       ZC400  2012-05-11  2200-01-01  etf
159919.XSHE       300ETF      300ETF  2012-05-28  2200-01-01  etf
159920.XSHE        恒生ETF       HSETF  2012-10-22  2200-01-01  etf
159921.XSHE         中小等权        ZXDQ  2013-01-31  2017-11-07  etf
159922.XSHE       500ETF      500ETF  2013-03-15  2200-01-01  etf
159923.XSHE       100ETF      100ETF  2013-03-05  2200-01-01  etf
159924.XSHE        300等权       300DQ  2013-06-05  2018-03-19  etf
159925.XSHE        南方300       NF300  2013-04-11  2200-01-01  etf
159926.XSHE        国债ETF       GZETF  2013-08-05  2200-01-01  etf
159927.XSHE      A300ETF     A300ETF  2013-08-16  2018-02-13  etf
159928.XSHE        消费ETF       XFETF  2013-09-16  2200-01-01  etf
159929.XSHE        医药ETF       YYETF  2013-09-16  2200-01-01  etf
159930.XSHE        能源ETF       NYETF  2013-09-16  2200-01-01  etf
159931.XSHE        金融ETF       JRETF  2013-09-16  2200-01-01  etf
159932.XSHE      500深ETF     500SETF  2013-10-21  2200-01-01  etf
159933.XSHE        金地ETF       JDETF  2013-10-16  2200-01-01  etf
159934.XSHE        黄金ETF       HJETF  2013-12-16  2200-01-01  etf
159935.XSHE        景顺500       JS500  2014-01-21  2200-01-01  etf
159936.XSHE         可选消费        KXXF  2014-06-25  2200-01-01  etf
159937.XSHE       黄金9999        BSHJ  2014-09-01  2200-01-01  etf
159938.XSHE           医药        GFYY  2015-01-08  2200-01-01  etf
159939.XSHE         信息技术        XXJS  2015-02-05  2200-01-01  etf
159940.XSHE           金融        QZJR  2015-04-17  2200-01-01  etf
159941.XSHE        纳指ETF       NZ100  2015-07-13  2200-01-01  etf
159942.XSHE        中创100       ZC100  2015-06-25  2018-11-05  etf
159943.XSHE        深证ETF       SZETF  2015-07-08  2200-01-01  etf
159944.XSHE        材料ETF        QZCL  2015-07-06  2200-01-01  etf
159945.XSHE           能源        QZNY  2015-07-06  2200-01-01  etf
159946.XSHE         全指消费        QZXF  2015-07-13  2018-12-27  etf
159948.XSHE        创业板EF       CYBEF  2016-05-31  2200-01-01  etf
159949.XSHE        创业板50       CYB50  2016-07-22  2200-01-01  etf
159950.XSHE        深成指EF       SCZEF  2017-05-10  2019-07-11  etf
159951.XSHE         中关村A        ZGCA  2017-07-10  2200-01-01  etf
159952.XSHE        创业ETF       CYETF  2017-05-19  2200-01-01  etf
159953.XSHE        工业ETF       GYETF  2017-07-14  2020-12-16  etf
159954.XSHE        H股ETF       HGETF  2018-03-15  2200-01-01  etf
159955.XSHE         创业板E        CYBE  2017-08-23  2200-01-01  etf
159956.XSHE         创业板F        CYBF  2018-03-07  2200-01-01  etf
159957.XSHE        创业板HX       CYBHX  2018-01-04  2200-01-01  etf
159958.XSHE        创业板ET       CYBET  2018-01-19  2200-01-01  etf
159959.XSHE        央企ETF        YHYQ  2019-01-18  2200-01-01  etf
159960.XSHE         恒生国企        HSGQ  2018-10-22  2200-01-01  etf
159961.XSHE         深100        S100  2018-12-19  2200-01-01  etf
159962.XSHE         四川国改        SCGG  2019-04-18  2200-01-01  etf
159963.XSHE         恒生中国        HSZG  2019-03-26  2021-05-24  etf
159964.XSHE        创业板PA       CYBPA  2019-04-19  2200-01-01  etf
159965.XSHE         央视50        YS50  2019-04-24  2200-01-01  etf
159966.XSHE          创蓝筹         CLC  2019-07-15  2200-01-01  etf
159967.XSHE          创成长         CCZ  2019-07-15  2200-01-01  etf
159968.XSHE     ZZ500ETF    ZZ500ETF  2019-10-31  2200-01-01  etf
159969.XSHE        深100P       S100P  2019-08-28  2200-01-01  etf
159970.XSHE       深100ET      S100ET  2020-01-10  2200-01-01  etf
159971.XSHE        创业100       CYBFG  2019-07-02  2200-01-01  etf
159972.XSHE         5年地债        5NDZ  2019-11-08  2200-01-01  etf
159973.XSHE        民企100       MQ100  2019-08-09  2200-01-01  etf
159974.XSHE         央企创新        YQCX  2019-12-18  2200-01-01  etf
159975.XSHE       深100SZ      S100SZ  2020-01-02  2200-01-01  etf
159976.XSHE        湾创ETF       WCETF  2020-01-17  2200-01-01  etf
159977.XSHE        创业板TH       CYBTH  2019-09-27  2200-01-01  etf
159978.XSHE        湾区ETF       WQETF  2020-04-14  2200-01-01  etf
159979.XSHE        湾创100       WC100  2020-02-14  2200-01-01  etf
159980.XSHE        有色ETF        YSQH  2019-12-24  2200-01-01  etf
159981.XSHE         能源化工        NYHG  2020-01-17  2200-01-01  etf
159982.XSHE        中证500       ZZ500  2020-02-20  2200-01-01  etf
159983.XSHE          大湾区         DWQ  2020-04-23  2200-01-01  etf
159984.XSHE         湾区基金        WQJJ  2020-01-17  2200-01-01  etf
159985.XSHE        豆粕ETF       DPETF  2019-12-05  2200-01-01  etf
159986.XSHE        消费100       XF100  2020-01-20  2200-01-01  etf
159987.XSHE        创新ETF       CXETF  2019-11-18  2200-01-01  etf
159988.XSHE        粤债ETF       YZETF  2020-05-29  2200-01-01  etf
159990.XSHE         小盘价值        XPJZ  2020-01-20  2200-01-01  etf
159991.XSHE          创大盘         CDP  2020-04-24  2200-01-01  etf
159992.XSHE          创新药         CXY  2020-04-10  2200-01-01  etf
159993.XSHE         龙头券商        LTQS  2020-02-07  2200-01-01  etf
159994.XSHE        5GETF       5GETF  2020-02-28  2200-01-01  etf
159995.XSHE        芯片ETF       XPETF  2020-02-10  2200-01-01  etf
159996.XSHE        家电ETF       JDETF  2020-03-16  2200-01-01  etf
159997.XSHE        电子ETF       DZETF  2020-03-20  2200-01-01  etf
159998.XSHE          计算机         JSJ  2020-04-13  2200-01-01  etf
159999.XSHE        永赢500       YY500  2020-08-12  2200-01-01  etf
510010.XSHG        治理ETF       ZLETF  2009-12-15  2200-01-01  etf
510020.XSHG        超大ETF       CDETF  2010-03-19  2200-01-01  etf
510030.XSHG        价值ETF       JZETF  2010-05-28  2200-01-01  etf
510050.XSHG        50ETF       50ETF  2005-02-23  2200-01-01  etf
510060.XSHG        央企ETF       YQETF  2009-10-27  2200-01-01  etf
510070.XSHG        民企ETF       MQETF  2010-10-29  2020-08-12  etf
510090.XSHG        责任ETF       ZRETF  2010-08-09  2200-01-01  etf
510100.XSHG      SZ50ETF     SZ50ETF  2019-10-09  2200-01-01  etf
510110.XSHG        周期ETF       ZQETF  2010-11-15  2200-01-01  etf
510120.XSHG        非周ETF       FZETF  2011-06-08  2200-01-01  etf
510130.XSHG        中盘ETF       ZPETF  2010-06-23  2200-01-01  etf
510150.XSHG        消费ETF       XFETF  2011-02-25  2200-01-01  etf
510160.XSHG        小康ETF       XKETF  2010-11-01  2200-01-01  etf
510170.XSHG        商品ETF       SPETF  2011-01-25  2200-01-01  etf
510180.XSHG       180ETF      180ETF  2006-05-18  2200-01-01  etf
510190.XSHG        龙头ETF       LTETF  2011-01-10  2200-01-01  etf
510200.XSHG         上证券商        SZQS  2020-05-08  2200-01-01  etf
510210.XSHG        综指ETF       ZZETF  2011-03-25  2200-01-01  etf
510220.XSHG        中小ETF       ZXETF  2011-03-28  2200-01-01  etf
510230.XSHG        金融ETF       JRETF  2011-05-23  2200-01-01  etf
510260.XSHG        新兴ETF       XXETF  2011-06-08  2020-01-14  etf
510270.XSHG        国企ETF       GQETF  2011-08-18  2200-01-01  etf
510280.XSHG        成长ETF       CZETF  2011-10-18  2019-09-27  etf
510290.XSHG       380ETF      380ETF  2011-11-08  2200-01-01  etf
510300.XSHG       300ETF      300ETF  2012-05-28  2200-01-01  etf
510310.XSHG     HS300ETF    HS300ETF  2013-03-25  2200-01-01  etf
510330.XSHG        华夏300       HX300  2013-01-16  2200-01-01  etf
510350.XSHG        工银300       GY300  2019-08-16  2200-01-01  etf
510360.XSHG        广发300       GF300  2015-09-09  2200-01-01  etf
510370.XSHG        兴业300       XY300  2020-10-27  2200-01-01  etf
510380.XSHG        国寿300       GS300  2018-02-07  2200-01-01  etf
510390.XSHG        平安300       PA300  2018-01-26  2200-01-01  etf
510410.XSHG        资源ETF       ZYETF  2012-05-11  2200-01-01  etf
510420.XSHG     180EWETF    180EWETF  2012-07-09  2019-11-07  etf
510430.XSHG         50等权        50DQ  2012-09-24  2020-12-17  etf
510440.XSHG        500沪市       500HS  2012-10-08  2200-01-01  etf
510450.XSHG      180高ETF     180GETF  2013-08-01  2016-08-23  etf
510500.XSHG       500ETF      500ETF  2013-03-15  2200-01-01  etf
510510.XSHG        广发500       GF500  2013-05-24  2200-01-01  etf
510520.XSHG        诺安500       NA500  2014-03-10  2019-10-30  etf
510530.XSHG        工银500       GY500  2020-01-03  2200-01-01  etf
510550.XSHG        方正500       FZ500  2019-01-16  2200-01-01  etf
510560.XSHG        国寿500       GS500  2015-07-03  2200-01-01  etf
510570.XSHG   兴业中证500ETF  XYZZ500ETF  2020-08-12  2200-01-01  etf
510580.XSHG     ZZ500ETF    ZZ500ETF  2015-09-14  2200-01-01  etf
510590.XSHG        平安500       PA500  2018-05-04  2200-01-01  etf
510600.XSHG       沪50ETF      H50ETF  2018-09-20  2200-01-01  etf
510610.XSHG         能源行业        NYHY  2013-05-08  2016-07-05  etf
510620.XSHG         材料行业        CLHY  2013-05-08  2016-08-12  etf
510630.XSHG         消费行业        XFHY  2013-05-08  2200-01-01  etf
510650.XSHG         金融行业        JRHY  2013-05-08  2200-01-01  etf
510660.XSHG         医药行业        YYHY  2013-05-08  2200-01-01  etf
510680.XSHG         万家50        WJ50  2013-12-02  2200-01-01  etf
510690.XSHG        180金融       180JR  2020-06-22  2200-01-01  etf
510700.XSHG        百强ETF       BQETF  2013-05-31  2016-05-12  etf
510710.XSHG       上50ETF      S50ETF  2015-06-15  2200-01-01  etf
510760.XSHG        上证ETF       SZETF  2020-09-09  2200-01-01  etf
510800.XSHG         上证50        SZ50  2018-01-15  2200-01-01  etf
510810.XSHG         上海国企        SHGQ  2016-08-29  2200-01-01  etf
510820.XSHG         上海改革        SHGG  2019-07-09  2019-08-19  etf
510850.XSHG        工银上50       GYS50  2019-03-06  2200-01-01  etf
510860.XSHG         兴业50        XY50  2021-01-12  2200-01-01  etf
510880.XSHG        红利ETF       HLETF  2007-01-18  2200-01-01  etf
510890.XSHG         红利低波        HLDB  2019-06-24  2200-01-01  etf
510900.XSHG        H股ETF       HGETF  2012-10-22  2200-01-01  etf
511000.XSHG         长三角债        CSJZ  2020-10-29  2021-04-16  etf
511010.XSHG        国债ETF       GZETF  2013-03-25  2200-01-01  etf
511020.XSHG         活跃国债        HYGZ  2019-02-22  2200-01-01  etf
511030.XSHG          公司债         GSZ  2019-03-22  2200-01-01  etf
511050.XSHG         兴业地债      DFZETF  2020-07-30  2200-01-01  etf
511060.XSHG         5年地债        5NDZ  2019-12-12  2200-01-01  etf
511180.XSHG         上证转债        SZZZ  2020-08-26  2200-01-01  etf
511210.XSHG        企债ETF       QZETF  2013-08-16  2018-01-25  etf
511220.XSHG        城投ETF       CTETF  2014-12-16  2200-01-01  etf
511230.XSHG          周期债         ZQZ  2017-04-21  2021-03-26  etf
511260.XSHG         十年国债        SNGZ  2017-08-24  2200-01-01  etf
511270.XSHG        10年地债       10NDZ  2018-11-22  2200-01-01  etf
511280.XSHG         中期信用        ZQXY  2018-05-31  2200-01-01  etf
511290.XSHG         国债十年        GZSN  2018-04-27  2020-10-29  etf
511310.XSHG          十年债         SNZ  2018-04-26  2200-01-01  etf
511360.XSHG      中证短融ETF     ZZDRETF  2020-09-25  2200-01-01  etf
511380.XSHG        转债ETF       ZZETF  2020-04-07  2200-01-01  etf
512000.XSHG        券商ETF       QSETF  2016-09-14  2200-01-01  etf
512010.XSHG        医药ETF       YYETF  2013-10-28  2200-01-01  etf
512040.XSHG         国信价值        GXJZ  2018-11-29  2200-01-01  etf
512070.XSHG         证券保险       FYETF  2014-07-18  2200-01-01  etf
512090.XSHG       MSCI易基      MSCIYJ  2018-06-01  2200-01-01  etf
512100.XSHG      1000ETF     1000ETF  2016-11-04  2200-01-01  etf
512110.XSHG         中证地产        ZZDC  2014-01-06  2017-01-12  etf
512120.XSHG         医药50        ZZYY  2014-01-06  2200-01-01  etf
512150.XSHG       A50ETF      A50ETF  2019-01-21  2200-01-01  etf
512160.XSHG       MSCI基金      MSCIJJ  2018-04-27  2200-01-01  etf
512170.XSHG        医疗ETF       YLETF  2019-06-17  2200-01-01  etf
512180.XSHG       建信MSCI      JXMSCI  2018-05-21  2200-01-01  etf
512190.XSHG         之江凤凰        ZJFH  2019-09-09  2200-01-01  etf
512200.XSHG        地产ETF         FDC  2017-09-25  2200-01-01  etf
512210.XSHG         景顺食品        JSSP  2014-08-19  2018-08-30  etf
512220.XSHG        科技150       JSTMT  2014-08-19  2200-01-01  etf
512230.XSHG         景顺医药        JSYY  2014-08-19  2019-01-22  etf
512260.XSHG        500低波       500DB  2019-01-11  2200-01-01  etf
512270.XSHG        300低波       300DB  2019-03-29  2200-01-01  etf
512280.XSHG       景顺MSCI      JSMSCI  2018-05-25  2200-01-01  etf
512290.XSHG         生物医药        SWYY  2019-05-20  2200-01-01  etf
512300.XSHG        500医药       500YY  2014-12-18  2021-03-11  etf
512310.XSHG        工业ETF       500GY  2015-05-08  2021-04-15  etf
512320.XSHG       工银MSCI      GYMSCI  2020-08-07  2200-01-01  etf
512330.XSHG        信息ETF       500XX  2015-07-20  2200-01-01  etf
512340.XSHG        原料ETF       500YL  2015-05-15  2021-04-15  etf
512350.XSHG        福建ETF       FJETF  2020-09-10  2200-01-01  etf
512360.XSHG       MSCI国际      MSCIGJ  2018-07-20  2200-01-01  etf
512380.XSHG       MSCI中国      YHMSCI  2019-04-30  2200-01-01  etf
512390.XSHG       MSCI低波      MSCIDB  2018-07-13  2200-01-01  etf
512400.XSHG        有色ETF        YSJS  2017-09-01  2200-01-01  etf
512480.XSHG          半导体         BDT  2019-06-12  2200-01-01  etf
512500.XSHG        中证500       ZZ500  2015-05-29  2200-01-01  etf
512510.XSHG       ETF500      ETF500  2015-06-12  2200-01-01  etf
512520.XSHG      MSCIETF     MSCIETF  2018-05-18  2200-01-01  etf
512530.XSHG        300红利       300HL  2019-09-23  2200-01-01  etf
512550.XSHG        富时A50       FSA50  2017-08-07  2200-01-01  etf
512560.XSHG         中证军工        ZZJG  2017-07-28  2200-01-01  etf
512570.XSHG         中证证券        ZZZQ  2017-08-11  2200-01-01  etf
512580.XSHG        环保ETF       HBETF  2017-02-28  2200-01-01  etf
512590.XSHG          高股息         GGX  2019-03-08  2200-01-01  etf
512600.XSHG         主要消费        ZYXF  2014-07-25  2200-01-01  etf
512610.XSHG         医药卫生        YYWS  2014-07-25  2200-01-01  etf
512640.XSHG         金融地产        JRDC  2014-07-25  2200-01-01  etf
512650.XSHG          长三角         CSJ  2019-10-25  2200-01-01  etf
512660.XSHG        军工ETF       JGETF  2016-08-08  2200-01-01  etf
512670.XSHG        国防ETF       GFETF  2019-08-01  2200-01-01  etf
512680.XSHG         军工基金        JGJJ  2016-10-14  2200-01-01  etf
512690.XSHG         酒ETF        JETF  2019-05-06  2200-01-01  etf
512700.XSHG         银行基金        YHJJ  2017-07-26  2200-01-01  etf
512710.XSHG         军工龙头        JGLT  2019-08-26  2200-01-01  etf
512720.XSHG          计算机         JSJ  2019-08-16  2200-01-01  etf
512730.XSHG       银行FUND      YHFUND  2020-02-07  2200-01-01  etf
512750.XSHG        基本面50       JBM50  2019-07-05  2200-01-01  etf
512760.XSHG        芯片ETF       BDT50  2019-06-12  2200-01-01  etf
512770.XSHG         战略新兴        ZLXX  2018-08-16  2200-01-01  etf

In [7]:
nd = df2[df2['end_date']=='2200-01-01']
nd.to_csv('./csv_files/nss.csv')